server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?autoReconnect=true&useServerPreparedStmts=false&rewriteBatchedStatements=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: test1
    password: test111
    driver-class-name: com.mysql.cj.jdbc.Driver


  cloud:
    nacos:
      server-addr: localhost:18848
  application:
    name: user-service

mybatis:
  type-aliases-package: cn.zx.zx.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.zx: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

jwt:
  key: kadifpeiajifd2346aija41676g7363jir343tj6rnfad36744kfjk4gaie78878wjeiqpoieruig9897jidafjdkfj

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.shop.user_service
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn