server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway-service # 服务名称
  cloud:
    nacos:
      server-addr: localhost:18848 # nacos地址
    gateway:

      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            maxAge: 3600

      routes: # 网关路由配置

        - id: user-service # 用户id，自定义，只要唯一即可
          uri: lb://user-service # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/api/user/**  # 这个是按照路径匹配，只要以/user/开头就符合要求
          filters:
            - StripPrefix= 1
            - AddRequestHeader=x-forward-from-gateway, ${gateway.key}

        - id: order-service # 订单id
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix= 1
            - AddRequestHeader=x-forward-from-gateway, ${gateway.key}

        - id: product-service # 商品id
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix= 1
            - AddRequestHeader=x-forward-from-gateway, ${gateway.key}

        # 商品微服务
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/api/productSku/**
          filters:
            - StripPrefix= 1
            - AddRequestHeader=x-forward-from-gateway, ${gateway.key}





jwt:
  key: kadifpeiajifd2346aija41676g7363jir343tj6rnfad36744kfjk4gaie78878wjeiqpoieruig9897jidafjdkfj

gateway:
  key: kdajfopdifauediafejnafdifu-90q849qjeru4q90uq9rje