server:
  port: 9001
spring:
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_zx?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.zx.domain.entity.product
  global-config:
    datacenter-id: 1
    workerId: 1
  configuration:
    map-underscore-to-camel-case: true  #是否关闭驼峰到下划线的映射
    cache-enabled: false  #是否开启二级缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印sql语句
